### ISSUE TITLE
update package.json for koa2

### ISSUE THREAD

**Issue by sorahn** [dominicbarnes/koa-file-router#1]
If you update `koa-router` in the dependencies to `^7.4.0` this module works perfectly with koa2 and async.

Alternatively if you want to remain version agnostic, you could set it as a peer dependency :)

**Comment by dominicbarnes** [comment]
koa is only a dev-dependency, so is this a problem?

**Comment by sorahn** [comment]
It's listed as a regular dependency: https://github.com/dominicbarnes/koa-file-router/blob/master/package.json#L19

**Comment by sorahn** [comment]
Oh, you said just koa.  No, it doesn't complain about `koa`, but the version of `koa-router` in your package.json has deprecation warnings for koa2, and will not be compatible with the next version.

**Comment by dominicbarnes** [comment]
Oh, I see what you mean! I'd rather just update to koa2 behind a major bump.

**Comment by dominicbarnes** [comment]
Bleh, just upgrading everything across the board didn't quite work. I don't really develop on node anymore, much less koa, so I would really like a PR here if you've got the time.

**Comment by sorahn** [comment]
I will put one together today at work!

Thanks

**Comment by dominicbarnes** [comment]
Just tagged v1.0.0 with koa2 support!
